kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-store
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi